package theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF516600)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD3EE80)
val md_theme_light_onPrimaryContainer = Color(0xFF161E00)
val md_theme_light_secondary = Color(0xFF5B6146)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE0E6C4)
val md_theme_light_onSecondaryContainer = Color(0xFF181E08)
val md_theme_light_tertiary = Color(0xFF3A665E)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFBCECE1)
val md_theme_light_onTertiaryContainer = Color(0xFF00201B)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFEFCF4)
val md_theme_light_onBackground = Color(0xFF1B1C17)
val md_theme_light_surface = Color(0xFFFEFCF4)
val md_theme_light_onSurface = Color(0xFF1B1C17)
val md_theme_light_surfaceVariant = Color(0xFFE3E4D3)
val md_theme_light_onSurfaceVariant = Color(0xFF46483C)
val md_theme_light_outline = Color(0xFF76786B)
val md_theme_light_inverseOnSurface = Color(0xFFF3F1E9)
val md_theme_light_inverseSurface = Color(0xFF30312B)
val md_theme_light_inversePrimary = Color(0xFFB7D167)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF516600)
val md_theme_light_outlineVariant = Color(0xFFC7C8B8)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFB7D167)
val md_theme_dark_onPrimary = Color(0xFF293500)
val md_theme_dark_primaryContainer = Color(0xFF3C4D00)
val md_theme_dark_onPrimaryContainer = Color(0xFFD3EE80)
val md_theme_dark_secondary = Color(0xFFC4CAA9)
val md_theme_dark_onSecondary = Color(0xFF2D331C)
val md_theme_dark_secondaryContainer = Color(0xFF434930)
val md_theme_dark_onSecondaryContainer = Color(0xFFE0E6C4)
val md_theme_dark_tertiary = Color(0xFFA1D0C6)
val md_theme_dark_onTertiary = Color(0xFF033730)
val md_theme_dark_tertiaryContainer = Color(0xFF214E47)
val md_theme_dark_onTertiaryContainer = Color(0xFFBCECE1)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1B1C17)
val md_theme_dark_onBackground = Color(0xFFE4E3DB)
val md_theme_dark_surface = Color(0xFF1B1C17)
val md_theme_dark_onSurface = Color(0xFFE4E3DB)
val md_theme_dark_surfaceVariant = Color(0xFF46483C)
val md_theme_dark_onSurfaceVariant = Color(0xFFC7C8B8)
val md_theme_dark_outline = Color(0xFF909284)
val md_theme_dark_inverseOnSurface = Color(0xFF1B1C17)
val md_theme_dark_inverseSurface = Color(0xFFE4E3DB)
val md_theme_dark_inversePrimary = Color(0xFF516600)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFB7D167)
val md_theme_dark_outlineVariant = Color(0xFF46483C)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF2D321D)

val LightGreen = Color(0xFF8DA25A)
val DarkGreen = Color(0xFF2D321D)

val RedPantone = Color(0xFFEF233C)
